apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-auth
  namespace: event-auth
  labels:
    app: event-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: event-auth
  template:
    metadata:
      labels:
        app: event-auth
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:24.0.3
          imagePullPolicy: Always
          args: ["start-dev"]
          ports:
            - containerPort: 8080
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KC_DB
              value: postgres
            - name: KC_DB_URL
              value: jdbc:postgresql://postgres.event-auth.svc.cluster.local:5432/keycloak_db
            - name: KC_DB_USERNAME
              value: keycloak
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

